#!/usr/bin/env bash
# heirloom-register.sh — register the Heirloom extension against the deployed
# HeirloomVault, instead of deploying a fresh InstructionSender.
#
# This is the one place Heirloom diverges from the scaffold. `pre-build.sh`
# deploys its own InstructionSender and registers the extension against that
# address. Heirloom cannot use it: HeirloomVault *is* the InstructionSender, and
# TeeExtensionRegistry rejects sendInstructions from any address other than the
# one bound at registration. Registering against the scaffold's contract would
# leave every HEIRLOOM instruction reverting, and setExtensionId() on the vault
# would fail with ExtensionNotFound because it scans for its own address.
#
# Run inside the tools image (Go + Foundry are not needed on the host):
#   docker build -f Dockerfile.tools -t heirloom-tools .
#   docker run --rm -v "$PWD:/w" -w /w heirloom-tools ./scripts/heirloom-register.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

GREEN='\033[0;32m'; RED='\033[0;31m'; CYAN='\033[0;36m'; NC='\033[0m'
log()  { echo -e "${GREEN}[heirloom-register]${NC} $*"; }
step() { echo -e "\n${CYAN}=== $* ===${NC}"; }
die()  { echo -e "${RED}[heirloom-register] ERROR:${NC} $*" >&2; exit 1; }

# The vault is already deployed and owns its own instruction routing.
HEIRLOOM_VAULT="${HEIRLOOM_VAULT:-0x250B6F94F8779a9CfbD826FD6CCF0a9845DcEb3A}"

[[ -f "$PROJECT_DIR/.env" ]] && { set -a; source "$PROJECT_DIR/.env"; set +a; }

CHAIN_URL="${CHAIN_URL:-https://coston2-api.flare.network/ext/C/rpc}"
ADDRESSES_FILE="${ADDRESSES_FILE:-./config/coston2/deployed-addresses.json}"
[[ "$ADDRESSES_FILE" != /* ]] && ADDRESSES_FILE="$PROJECT_DIR/${ADDRESSES_FILE#./}"
CONFIG_OUTPUT="$PROJECT_DIR/config/extension.env"

[[ -f "$ADDRESSES_FILE" ]] || die "Addresses file not found: $ADDRESSES_FILE"
[[ -n "${DEPLOYMENT_PRIVATE_KEY:-}" ]] || die "DEPLOYMENT_PRIVATE_KEY is not set — check .env"

log "Chain:      $CHAIN_URL"
log "Addresses:  $ADDRESSES_FILE"
log "Vault:      $HEIRLOOM_VAULT  (acts as the InstructionSender)"

if [[ -f "$CONFIG_OUTPUT" ]] && grep -q "^EXTENSION_ID=" "$CONFIG_OUTPUT" 2>/dev/null && [[ "${FORCE:-0}" != "1" ]]; then
    log "$CONFIG_OUTPUT already exists — reusing it."
    sed -n 's/^/    /p' "$CONFIG_OUTPUT"
    echo ""
    echo "  Re-registering mints a NEW extension id and orphans any TEE already"
    echo "  bound to the old one (post-build then fails with MachineManager.TooMany)."
    echo "  Set FORCE=1 only if you intend a fresh extension."
    exit 0
fi

# Bindings are .gitignored and imported transitively by register-extension, so
# they must exist before `go run` will compile — even though we deploy nothing.
step "Generate Go bindings"
"$SCRIPT_DIR/generate-bindings.sh" || die "Binding generation failed"

step "Register extension against HeirloomVault"
cd "$PROJECT_DIR/go/tools"
EXTENSION_ID=$(go run ./cmd/register-extension \
    -a "$ADDRESSES_FILE" \
    -c "$CHAIN_URL" \
    --instructionSender "$HEIRLOOM_VAULT" | tail -1) \
    || die "Registration failed"

[[ "$EXTENSION_ID" =~ ^0x[0-9a-fA-F]{64}$ ]] \
    || die "register-extension returned an unexpected id: '$EXTENSION_ID'"

mkdir -p "$(dirname "$CONFIG_OUTPUT")"
cat > "$CONFIG_OUTPUT" <<EOF
# Auto-generated by heirloom-register.sh — do not edit manually
EXTENSION_ID=$EXTENSION_ID
INSTRUCTION_SENDER=$HEIRLOOM_VAULT
EOF

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN} Extension registered${NC}"
echo -e "${GREEN}========================================${NC}"
echo "  EXTENSION_ID         $EXTENSION_ID"
echo "  INSTRUCTION_SENDER   $HEIRLOOM_VAULT  (HeirloomVault)"
echo "  Config file          $CONFIG_OUTPUT"
echo ""
echo "  Next: start the stack on the VPS, then run post-build.sh to register the"
echo "  TEE machine, then call setExtensionId() and setTeeAddress() on the vault."
